/**
 * Circuit outline drawn from OpenStreetMap (see src/lib/track-outline.ts).
 * The SVG is generated by us from coordinates only, so it is safe to inline.
 */
export default function TrackOutline({ svg, className = '' }: { svg: string; className?: string }) {
  return (
    <figure className={className}>
      <div className="w-full [&>svg]:w-full [&>svg]:h-auto" dangerouslySetInnerHTML={{ __html: svg }} />
      <figcaption className="mt-1 text-right text-[10px] text-[var(--text-muted)]">
        Track: ©{' '}
        <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer" className="underline underline-offset-2">
          OpenStreetMap
        </a>{' '}
        contributors
      </figcaption>
    </figure>
  );
}
