import 'dotenv/config';
import { drizzle } from 'drizzle-orm/mysql2';
import mysql from 'mysql2/promise';
import { experiences, experience_windows, experience_windows_map, races } from '../src/lib/db/schema';
import { eq } from 'drizzle-orm';
import { buildAffiliateUrl } from '../src/lib/affiliates';

/**
 * Seed script for 42 Shanghai experiences (8–9 per category)
 *
 * Categories: food, culture, adventure, daytrip, nightlife
 * Each experience is mapped to the experience windows where it fits
 * based on duration and time-of-day suitability.
 *
 * Depends on: seed-shanghai-race.ts (shanghai-2026 race + 8 experience windows)
 * Run: npx tsx scripts/seed-shanghai-experiences.ts
 */

interface ExperienceSeed {
  title: string;
  description: string;
  short_description: string;
  abstract?: string;
  category: 'food' | 'culture' | 'adventure' | 'daytrip' | 'nightlife';
  duration_hours: string;
  duration_label: string;
  price_amount: string;
  price_currency: string;
  price_label: string;
  rating: string;
  review_count: number;
  image_url: string;
  image_emoji: string;
  affiliate_base_url: string;
  affiliate_product_id: string;
  is_featured: boolean;
  tag: string | null;
  sort_order: number;
  windows: string[];
}

const EXPERIENCES: ExperienceSeed[] = [
  // =============================================
  // FOOD (8)
  // =============================================
  {
    title: 'Shanghai: 3-Hour Local Food Tasting Tour',
    description: 'Sample 10–15 traditional Shanghai dishes on this guided food tasting tour through the former French Concession. From steaming soup dumplings (xiao long bao) to century-old dessert shops, your local guide leads you through family-run eateries that have fed generations. Try scallion pancakes, stinky tofu, and sweet osmanthus cakes while learning the stories behind each dish on this immersive culinary walk.',
    short_description: 'Sample 10–15 traditional Shanghai dishes on a guided food tasting tour through the French Concession with a local guide.',
    abstract: 'Sample 10-15 traditional dishes in the French Concession — best dumplings in the city plus dessert stops. A$112 · 3 hrs · Perfect to kick off race weekend before FP1.',
    category: 'food',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '112.00',
    price_currency: 'AUD',
    price_label: 'A$112',
    rating: '4.9',
    review_count: 806,
    image_url: 'https://cdn.getyourguide.com/img/tour/b66b9b343feb8344.jpeg/medium.jpg',
    image_emoji: '🥟',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-3-hour-authentic-downtown-local-food-tasting-t68420/',
    affiliate_product_id: 't68420',
    is_featured: true,
    tag: 'Most Popular',
    sort_order: 1,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Half-Day Biking and Local Food Tour',
    description: 'Explore Shanghai\'s historic neighborhoods by bicycle on this half-day guided tour combining sightseeing with authentic snack stops. Ride through lanes and parks while your guide shares stories of Old Shanghai. Stop at street stalls and local eateries to sample scallion pancakes, rice dumplings, and other Shanghai staples you\'d never find on your own.',
    short_description: 'Guided bicycle tour through Shanghai\'s historic neighborhoods with local food stops along the way.',
    abstract: 'Half-day guided bicycle ride through Shanghai with stops for local snacks — history from behind the handlebars. A$106 · 3 hrs · Fits any F1 practice morning.',
    category: 'food',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '106.00',
    price_currency: 'AUD',
    price_label: 'A$106',
    rating: '4.9',
    review_count: 170,
    image_url: 'https://cdn.getyourguide.com/img/tour/4c9b83e2fd08a7a5.jpeg/medium.jpg',
    image_emoji: '🍜',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-half-day-biking-and-local-food-tour-t15839/',
    affiliate_product_id: 't15839',
    is_featured: false,
    tag: null,
    sort_order: 2,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Evening Walking Food Tour',
    description: 'Join a local insider and get off the beaten path on this evening walking food tour through the French Concession. Discover small, family-run eateries that prepare their dishes just as they have for generations. You\'ll visit local haunts away from tourist traps — authentic noodle bars, hole-in-the-wall dumpling kitchens, and neighbourhood dessert stalls that light up the streets after dark.',
    short_description: 'Evening guided walking food tour through Shanghai\'s French Concession with stops at family-run local eateries.',
    abstract: 'Local insider guide off the beaten path — family-run eateries in the French Concession after dark. A$97 · 3.5 hrs · Ideal post-qualifying or post-practice evening.',
    category: 'food',
    duration_hours: '3.5',
    duration_label: '3.5 hrs',
    price_amount: '97.00',
    price_currency: 'AUD',
    price_label: 'A$97',
    rating: '4.9',
    review_count: 115,
    image_url: 'https://cdn.getyourguide.com/img/tour/915944a10a44e8f3fb8aedf4fa4d55578cbff41950a2f9693e66a05ace8efadd.jpg/medium.jpg',
    image_emoji: '🍜',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-evening-walking-food-tour-t260112/',
    affiliate_product_id: 't260112',
    is_featured: false,
    tag: null,
    sort_order: 3,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race', 'sun-morning'],
  },
  {
    title: 'Late Night Food Tour in French Concession',
    description: 'Experience an authentic taste of Shanghai after dark in the former French Concession. Sample a dozen traditional Shanghai dishes — noodles, steamed buns, dumplings, barbecue skewers, and craft beer — at stalls and restaurants that come alive as the city winds down. A late-night culinary adventure for those who want to eat like a real Shanghainese local.',
    short_description: 'Late-night food tour through the French Concession sampling a dozen Shanghai dishes from noodles to dumplings to craft beer.',
    abstract: 'A dozen traditional Shanghai dishes after dark — noodles, buns, dumplings, barbecue, and craft beer in the French Concession. A$124 · 3 hrs · Best on F1 Friday and Saturday evenings.',
    category: 'food',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '124.00',
    price_currency: 'AUD',
    price_label: 'A$124',
    rating: '4.9',
    review_count: 31,
    image_url: 'https://cdn.getyourguide.com/img/tour/7d58e0f4e0ba991b.jpeg/medium.jpg',
    image_emoji: '🍺',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/late-night-food-tour-in-shanghai-s-french-concession-t518193/',
    affiliate_product_id: 't518193',
    is_featured: false,
    tag: null,
    sort_order: 4,
    windows: ['fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Song Dynasty Tea Ceremony Experience',
    description: 'Step into the Song Dynasty (960–1279 AD) and discover the ancient art of powdered tea whisking. Immerse yourself in China\'s centuries-old tea tradition — a UNESCO-listed intangible cultural heritage. Your host walks you through the ritual of matcha preparation using authentic Song Dynasty techniques, whisking the tea to a fine froth in a traditional bowl. A meditative and uniquely Chinese experience.',
    short_description: 'Hands-on Song Dynasty tea ceremony experience exploring China\'s centuries-old UNESCO-listed tea culture.',
    abstract: 'Song Dynasty tea ceremony with UNESCO-listed intangible cultural heritage — whisking matcha like it\'s the 11th century. A$110 · 1.5 hrs · Perfect for the F1 session gaps.',
    category: 'food',
    duration_hours: '1.5',
    duration_label: '1.5 hrs',
    price_amount: '110.00',
    price_currency: 'AUD',
    price_label: 'A$110',
    rating: '5.0',
    review_count: 10,
    image_url: 'https://cdn.getyourguide.com/img/tour/a10978c45c93c31874b39a610d2960049efedfa0268ff6c3ec1cd09205467742.jpg/medium.jpg',
    image_emoji: '🍵',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-song-dynasty-tea-ceremony-experience-t939284/',
    affiliate_product_id: 't939284',
    is_featured: false,
    tag: null,
    sort_order: 5,
    windows: ['fri-gap', 'sat-gap', 'fri-morning', 'sat-morning', 'post-race'],
  },
  {
    title: 'Shanghai: Jade Buddha Temple and Local Food Tour',
    description: 'Let a professional architect guide you through the serene Jade Buddha Temple before exploring Shanghai\'s most authentic street food. After the temple, your local guide takes you to neighbourhood eateries that only locals know — xiaolongbao from a family kitchen, wonton soup at a street corner stall, and sweet red bean pastries from a decades-old bakery. A rare combination of culture and cuisine.',
    short_description: 'Guided tour of the Jade Buddha Temple followed by authentic Shanghai street food at local neighbourhood haunts.',
    abstract: 'Jade Buddha Temple with an architect guide, then authentic street food at local haunts you\'d never find alone. A$48 · 3 hrs · Great start to race weekend.',
    category: 'food',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '48.00',
    price_currency: 'AUD',
    price_label: 'A$48',
    rating: '5.0',
    review_count: 5,
    image_url: 'https://cdn.getyourguide.com/img/tour/5ea07dd89f321d3e203bfb540f5e7bd3d2d101cef18444a74a580ccf085f0609.jpg/medium.jpg',
    image_emoji: '🥟',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-jade-buddha-temple-and-local-food-tour-t1183941/',
    affiliate_product_id: 't1183941',
    is_featured: false,
    tag: null,
    sort_order: 6,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Dragon Beard Candy Making with a Chef',
    description: 'Discover the ancient art of Dragon Beard Candy making with a professional pastry chef. Stretch sugar into thousands of sweet, silky threads — the same technique passed down for over a thousand years in Chinese imperial kitchens. Learn the rich history behind this intricate confection and create your own magical treat to take home. A hands-on culinary workshop unlike anything you\'ll find in a restaurant.',
    short_description: 'Hands-on workshop learning the ancient art of Dragon Beard Candy making with a professional Shanghai pastry chef.',
    abstract: 'Ancient Chinese imperial sugar art — stretch sugar into thousands of silky threads with a pastry chef. A$53 · 2 hrs · A uniquely Shanghai culinary experience between sessions.',
    category: 'food',
    duration_hours: '2.0',
    duration_label: '2 hrs',
    price_amount: '53.00',
    price_currency: 'AUD',
    price_label: 'A$53',
    rating: '4.8',
    review_count: 6,
    image_url: 'https://cdn.getyourguide.com/img/tour/033743d596b3c43eeb0db182d16702d352c92f45bcb4b0717771ab91fafbe4c3.jpg/medium.jpg',
    image_emoji: '☕',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-dragon-beard-candy-making-with-a-chef-t988271/',
    affiliate_product_id: 't988271',
    is_featured: false,
    tag: null,
    sort_order: 7,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: After Dark Dinner and Huangpu River Night Cruise',
    description: 'Enjoy dinner like a local Shanghainese, then board the Huangpu River for a spectacular night cruise along one of the world\'s most photogenic skylines. Watch the Bund\'s colonial buildings and Pudong\'s futuristic towers illuminate the river in competing brilliance. Optionally ascend Shanghai Tower or the Oriental Pearl Tower for breathtaking elevated views after dinner — an unforgettable way to experience Shanghai after dark.',
    short_description: 'Local Shanghai dinner followed by a night cruise on the Huangpu River with illuminated Bund and Pudong skyline views.',
    abstract: 'Local dinner then Huangpu River night cruise past the illuminated Bund — optionally ascend Shanghai Tower for breathtaking views. A$177 · 4 hrs · The ultimate F1 evening experience.',
    category: 'food',
    duration_hours: '4.0',
    duration_label: '4 hrs',
    price_amount: '177.00',
    price_currency: 'AUD',
    price_label: 'A$177',
    rating: '5.0',
    review_count: 16,
    image_url: 'https://cdn.getyourguide.com/img/tour/15825e0d8c6ad44330ca446dd1ef7663c909ff99e4ad4c6ece7a53591bb9f825.jpg/medium.jpg',
    image_emoji: '🍜',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-after-dark-dinner-and-huangpu-river-night-cruise-t1054108/',
    affiliate_product_id: 't1054108',
    is_featured: false,
    tag: null,
    sort_order: 8,
    windows: ['fri-evening', 'sat-evening', 'post-race', 'sun-morning'],
  },

  // =============================================
  // CULTURE (9)
  // =============================================
  {
    title: 'Shanghai Highlights Walking Tour With A Real Local',
    description: 'Explore Shanghai\'s most iconic landmarks on a walking tour with a real local guide — not a professional tour operator. Visit the Bund promenade, the Old Town, and Yuyuan Bazaar while learning about the city\'s extraordinary evolution from fishing village to global megacity. Your guide shares personal stories and insider perspectives that no guidebook can replicate.',
    short_description: 'Walking tour of Shanghai\'s Bund, Old Town, and Yu Garden with a real local guide sharing personal insights.',
    abstract: 'Real local guide through the Bund, Old Town, and Yuyuan Bazaar — personal stories no guidebook captures. A$48 · 2.5 hrs · Great pre-FP1 warm-up.',
    category: 'culture',
    duration_hours: '2.5',
    duration_label: '2.5 hrs',
    price_amount: '48.00',
    price_currency: 'AUD',
    price_label: 'A$48',
    rating: '4.9',
    review_count: 153,
    image_url: 'https://cdn.getyourguide.com/img/tour/6df7068ca1339281aadbb07479e73016b236950343a53dc0000da010c8508ac8.jpg/medium.jpg',
    image_emoji: '🏛️',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-highlights-walking-tour-with-a-real-local-t835541/',
    affiliate_product_id: 't835541',
    is_featured: true,
    tag: 'Best Value',
    sort_order: 9,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'French Concession Walking Tour with Real Local',
    description: 'Explore the French Concession — Shanghai\'s most stylish and history-laden neighbourhood — with a real local guide who calls it home. Discover Art Deco mansions, secret laneways (longtang), revolutionary-era residences, and the best independent cafes and boutiques. Learn how this former foreign settlement shaped modern Shanghai\'s identity and why it remains the city\'s cultural heartbeat.',
    short_description: 'Walking tour of the French Concession with a local guide exploring Art Deco mansions, secret laneways, and historic residences.',
    abstract: 'Art Deco mansions, secret longtang laneways, and history of Shanghai\'s most stylish neighbourhood with a real local. A$48 · 2.5 hrs · Perfect post-practice afternoon.',
    category: 'culture',
    duration_hours: '2.5',
    duration_label: '2.5 hrs',
    price_amount: '48.00',
    price_currency: 'AUD',
    price_label: 'A$48',
    rating: '5.0',
    review_count: 40,
    image_url: 'https://cdn.getyourguide.com/img/tour/da2c932ed730b1dc3bb0d347bb3eac15f841f21ccfce4f8bce2f472a1cbc3562.jpg/medium.jpg',
    image_emoji: '🌸',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/french-concession-walking-tour-with-real-local-t858987/',
    affiliate_product_id: 't858987',
    is_featured: false,
    tag: null,
    sort_order: 10,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Yu Garden Admission Ticket',
    description: 'Explore the beauty of Yu Garden, a classical Chinese garden with over 400 years of history nestled in the heart of Shanghai\'s Old City. Wander through pavilions, rockeries, koi ponds, and ornate corridors that once served as the private garden of a Ming dynasty official. Surrounded by the modern city yet timeless in its design, it\'s one of the finest examples of classical Chinese garden architecture.',
    short_description: 'Admission ticket to Shanghai\'s historic Yu Garden — a classical Ming dynasty garden with 400 years of history.',
    abstract: 'Classical Chinese garden with 400+ years of history — pavilions, koi ponds, and rockeries in the heart of Old Shanghai. A$23 · 4 hrs · A must between F1 sessions.',
    category: 'culture',
    duration_hours: '4.0',
    duration_label: '4 hrs',
    price_amount: '23.00',
    price_currency: 'AUD',
    price_label: 'A$23',
    rating: '4.6',
    review_count: 260,
    image_url: 'https://cdn.getyourguide.com/img/tour/2b3cfaf2c57ef61b9a4f62bc7eaeed75b8e3386cc1ad4ac94e9297a9c83ddcaa.png/medium.jpg',
    image_emoji: '🌸',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-yu-garden-admission-ticket-t833781/',
    affiliate_product_id: 't833781',
    is_featured: false,
    tag: null,
    sort_order: 11,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race', 'sun-morning'],
  },
  {
    title: 'Shanghai: Royal Banquet with Chinese Cultural Performance',
    description: 'Experience an imperial royal banquet complete with an elaborate Chinese cultural performance of traditional music and dance. Guests are dressed in royal attire for a photo session before dining on traditional banquet dishes in a magnificent setting designed to recreate the grandeur of China\'s imperial courts. An extravagant cultural evening that blends food, art, and history.',
    short_description: 'Imperial royal banquet experience with Chinese traditional music and dance performance in full imperial court setting.',
    abstract: 'Imperial court banquet with traditional music, dance, and royal costumes — Shanghai\'s most theatrical cultural evening. A$164 · 2 hrs · Unforgettable post-qualifying night.',
    category: 'culture',
    duration_hours: '2.0',
    duration_label: '2 hrs',
    price_amount: '164.00',
    price_currency: 'AUD',
    price_label: 'A$164',
    rating: '4.7',
    review_count: 124,
    image_url: 'https://cdn.getyourguide.com/img/tour/f3a8889af9750114d5be5a869aa8889a8108e2239385f8e42c22bf0c27dc1893.jpg/medium.jpg',
    image_emoji: '🎭',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-royal-banquet-with-chinese-cultural-performance-t708769/',
    affiliate_product_id: 't708769',
    is_featured: false,
    tag: null,
    sort_order: 12,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: 4-Hour Private Customizable City Tour',
    description: 'Tick off Shanghai\'s greatest hits on your own terms with a private customizable 4-hour city tour. From the historic Bund to the ancient Yu Garden, from the charming French Concession to the futuristic Pudong skyline — design your itinerary with your private guide. Ideal for first-time visitors who want to cover the essentials without being locked into a group pace.',
    short_description: 'Private 4-hour Shanghai city tour fully customizable to your interests — Bund, Yu Garden, French Concession, and more.',
    abstract: 'Your Shanghai, your pace — private 4-hour tour from the Bund to Pudong skylines with a customizable itinerary. A$128 · 4 hrs · Best after qualifying.',
    category: 'culture',
    duration_hours: '4.0',
    duration_label: '4 hrs',
    price_amount: '128.00',
    price_currency: 'AUD',
    price_label: 'A$128',
    rating: '5.0',
    review_count: 99,
    image_url: 'https://cdn.getyourguide.com/img/tour/d596d441473b9e8f1f36e303d7a83b77ad156da35f9805246c3b2c8a3bcaefe7.jpg/medium.jpg',
    image_emoji: '🚶',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-4-hour-private-customizable-city-tour-t643133/',
    affiliate_product_id: 't643133',
    is_featured: false,
    tag: null,
    sort_order: 13,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race', 'sun-morning'],
  },
  {
    title: 'Shanghai: Yu Garden and City God Temple Walking Tour',
    description: 'Enjoy a 3-hour walking tour through Old Shanghai to discover the city\'s traditional architecture and spiritual heritage. Visit the famous Yu Garden\'s classical Chinese pavilions and then explore the City God Temple — a Taoist temple complex that has been the spiritual heart of Shanghai\'s Old City for centuries. Your guide explains local beliefs, rituals, and the temple\'s fascinating history.',
    short_description: 'Walking tour of Old Shanghai covering Yu Garden\'s classical pavilions and the historic City God Temple with a guide.',
    abstract: 'Old Shanghai walking tour — classical Yu Garden and the Taoist City God Temple that has anchored the Old City for centuries. A$85 · 3 hrs · A morning highlight between sessions.',
    category: 'culture',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '85.00',
    price_currency: 'AUD',
    price_label: 'A$85',
    rating: '4.9',
    review_count: 27,
    image_url: 'https://cdn.getyourguide.com/img/tour/3ec9f9aae89ff9b6.jpeg/medium.jpg',
    image_emoji: '🏛️',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/private-tour-with-yu-garden-and-the-city-god-s-temple-t392267/',
    affiliate_product_id: 't392267',
    is_featured: false,
    tag: null,
    sort_order: 14,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Tech Discovery Tour with Driverless Car Ride',
    description: 'Explore Shanghai\'s extraordinary tech scene on a tour of the Lujiazui financial district. Visit Shanghai Tower — the world\'s second-tallest building — ride in a fully autonomous driverless car through Pudong\'s futuristic streets, and interact with humanoid robots showcasing China\'s AI frontier. A mind-expanding look at the cutting-edge technology shaping Shanghai\'s future.',
    short_description: 'Tech tour of Lujiazui with a driverless car ride, humanoid robot encounters, and a visit to Shanghai Tower.',
    abstract: 'Shanghai Tower, autonomous driverless car, and humanoid robots in Lujiazui — China\'s AI frontier on one tour. A$138 · 4 hrs · Great post-practice evening activity.',
    category: 'culture',
    duration_hours: '4.0',
    duration_label: '4 hrs',
    price_amount: '138.00',
    price_currency: 'AUD',
    price_label: 'A$138',
    rating: '4.9',
    review_count: 48,
    image_url: 'https://cdn.getyourguide.com/img/tour/e7544e114cf51e4f936ad41f2b53790b45a7db00429235b40aec6af6364c6808.jpeg/medium.jpg',
    image_emoji: '🏙️',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-tech-discovery-tour-with-driverless-car-ride-t1085657/',
    affiliate_product_id: 't1085657',
    is_featured: false,
    tag: null,
    sort_order: 15,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race', 'sun-morning'],
  },
  {
    title: 'Shanghai: Private and Personalized Guided Tour',
    description: 'Explore Shanghai on your own terms with this private, fully personalized guided tour. Immerse yourself in local life as you visit famous attractions, uncover hidden gems, and try local dishes your guide selects just for you. Whether you want to focus on architecture, history, food, or shopping, your guide tailors every moment of the day to your interests and pace.',
    short_description: 'Fully personalized private Shanghai guided tour — famous attractions, hidden gems, and local food tailored to your interests.',
    abstract: 'Fully personalized private tour of Shanghai with a guide who tailors every stop to your interests — landmarks to hidden gems. A$213 · 8 hrs · The ultimate race-day morning before 15:00.',
    category: 'culture',
    duration_hours: '8.0',
    duration_label: '8 hrs',
    price_amount: '213.00',
    price_currency: 'AUD',
    price_label: 'A$213',
    rating: '4.9',
    review_count: 268,
    image_url: 'https://cdn.getyourguide.com/img/tour/3bbbcfdd185ffe8f3c8f4ab0634f9dbcead6a6d72d3148c1ebf77ab463a079da.jpg/medium.jpg',
    image_emoji: '🚶',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-private-and-personalized-guided-tour-t383323/',
    affiliate_product_id: 't383323',
    is_featured: false,
    tag: null,
    sort_order: 16,
    windows: ['sun-morning'],
  },
  {
    title: 'Shanghai One Day City Private Tour',
    description: 'Explore the old and modern Shanghai on a full-day private tour covering the city\'s greatest contrasts. Visit the famed Yu Garden and Jade Buddha Temple on the historic west side, then cross to Pudong for the top-of-the-world views at Shanghai Tower and the breathtaking Bund skyline. A comprehensive day that captures everything that makes Shanghai one of the world\'s most extraordinary cities.',
    short_description: 'Full-day private Shanghai city tour covering Yu Garden, Jade Buddha Temple, Shanghai Tower, and the iconic Bund.',
    abstract: 'Yu Garden, Jade Buddha Temple, Shanghai Tower, and the Bund in one full private day — Shanghai\'s greatest contrasts. A$222 · 8 hrs · The ideal race-day morning exploration.',
    category: 'culture',
    duration_hours: '8.0',
    duration_label: '8 hrs',
    price_amount: '222.00',
    price_currency: 'AUD',
    price_label: 'A$222',
    rating: '4.9',
    review_count: 181,
    image_url: 'https://cdn.getyourguide.com/img/tour/b7dc58284ac08c3c955c8bcb10db6ad33bcd849998350f85fb0ede2d7d97a6ea.jpg/medium.jpg',
    image_emoji: '🏛️',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/8-hour-shanghai-city-private-tour-by-german-speaking-guide-t639872/',
    affiliate_product_id: 't639872',
    is_featured: false,
    tag: null,
    sort_order: 17,
    windows: ['sun-morning'],
  },

  // =============================================
  // ADVENTURE (8)
  // =============================================
  {
    title: 'Shanghai: Circus World ERA Theatre Acrobatics Ticket',
    description: 'Head to the Shanghai ERA Theatre for an unforgettable acrobatics performance at one of the city\'s most celebrated venues. Talented performers execute extraordinary feats on bikes, motorcycles, and aerial apparatus in a jaw-dropping show that blends traditional Chinese acrobatics with modern theatrical production. The circus world comes alive in 90 minutes of pure spectacle.',
    short_description: 'Admission to Shanghai ERA Theatre\'s world-class acrobatics show featuring extraordinary aerial and motorcycle performances.',
    abstract: 'World-class Shanghai acrobatics — bikes, motorcycles, and aerial feats at the ERA Theatre. A$77 · 2 hrs · The perfect post-qualifying Friday or Saturday night treat.',
    category: 'adventure',
    duration_hours: '2.0',
    duration_label: '2 hrs',
    price_amount: '77.00',
    price_currency: 'AUD',
    price_label: 'A$77',
    rating: '4.9',
    review_count: 284,
    image_url: 'https://cdn.getyourguide.com/img/tour/ffb55de5c4a3af00366162e64eb7c49c8795573169f11eb66f26dd23857c5257.jpeg/medium.jpg',
    image_emoji: '🎪',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-circus-world-era-theatre-acrobatics-ticket-t695680/',
    affiliate_product_id: 't695680',
    is_featured: true,
    tag: 'Top Rated',
    sort_order: 18,
    windows: ['fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai Tower: Observation Deck Admission Ticket',
    description: 'Experience breathtaking views from the Top of Shanghai Observation Deck at the world\'s second-tallest building. Standing at 546 metres above ground on the 118th floor, the views span across the entire Pudong skyline, the Bund, and on clear days far into the Yangtze River delta. The observation deck features glass floors, interactive displays, and the world\'s fastest elevators.',
    short_description: 'Admission to Shanghai Tower\'s observation deck at 546m — panoramic views of Pudong, the Bund, and beyond.',
    abstract: 'World\'s second-tallest building — panoramic Shanghai views from 546 metres up, glass floors and the world\'s fastest lifts. A$67 · 2 hrs · Perfect practice-morning or race-day view.',
    category: 'adventure',
    duration_hours: '2.0',
    duration_label: '2 hrs',
    price_amount: '67.00',
    price_currency: 'AUD',
    price_label: 'A$67',
    rating: '4.6',
    review_count: 375,
    image_url: 'https://cdn.getyourguide.com/img/tour/07ff436c9a734507b3c3340b473dd4dcee0338e7b43dd49afd92aa0d4cff802d.png/medium.jpg',
    image_emoji: '🏙️',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-tower-observation-deck-admission-ticket-t833810/',
    affiliate_product_id: 't833810',
    is_featured: false,
    tag: null,
    sort_order: 19,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Ancient Water Town + Yu Garden + Bund by Bike/Escooter',
    description: 'Enjoy an exciting 7-hour ride through the history of Shanghai combining a bus trip to an ancient water town with cycling around the Bund and Yu Garden. Hop on a bus to reach the historic water town, explore its canals and stone bridges, then jump on a bike or e-scooter to cruise past the iconic Bund and through the Old Town. The best way to cover maximum Shanghai in one active adventure.',
    short_description: 'Active 7-hour Shanghai adventure combining a bus trip to an ancient water town with cycling the Bund and Yu Garden.',
    abstract: 'Ancient water town, Yu Garden, and the Bund — Shanghai in 7 hours from a bus seat and a bike saddle. A$119 · 7 hrs · The ultimate race-day morning adventure before 15:00.',
    category: 'adventure',
    duration_hours: '7.0',
    duration_label: '7 hrs',
    price_amount: '119.00',
    price_currency: 'AUD',
    price_label: 'A$119',
    rating: '4.7',
    review_count: 74,
    image_url: 'https://cdn.getyourguide.com/img/tour/1eef6f9e00804de897bedc653056a7f77fea1399243409748ba6473bc207ae13.jpg/medium.jpg',
    image_emoji: '🚴',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/yu-garden-bund-zhujiajiao-water-town-by-bus-escooter-t162459/',
    affiliate_product_id: 't162459',
    is_featured: false,
    tag: null,
    sort_order: 20,
    windows: ['sun-morning'],
  },
  {
    title: 'Shanghai: Wild Animal Park Ticket',
    description: 'Explore Shanghai Wild Animal Park and encounter exotic wildlife in a sprawling natural setting on the city\'s outskirts. Enjoy thrilling safari rides through open-range enclosures, interactive animal feeding sessions, and up-close encounters with rare and endangered species from around the world. One of Asia\'s most diverse wildlife parks, offering an adventure the whole family will remember.',
    short_description: 'Admission to Shanghai Wild Animal Park with safari rides, interactive feeding, and exotic wildlife encounters.',
    abstract: 'Shanghai Wild Animal Park — safari rides and exotic wildlife encounters in one of Asia\'s most diverse parks. A$56 · 4 hrs · A wild race-weekend morning option.',
    category: 'adventure',
    duration_hours: '4.0',
    duration_label: '4 hrs',
    price_amount: '56.00',
    price_currency: 'AUD',
    price_label: 'A$56',
    rating: '4.9',
    review_count: 43,
    image_url: 'https://cdn.getyourguide.com/img/tour/37e29d94317316153523d5ce4f09db7bb3e55dbf18e41acf118950dbc7e00d82.png/medium.jpg',
    image_emoji: '🐼',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-wild-animal-park-ticket-t832461/',
    affiliate_product_id: 't832461',
    is_featured: false,
    tag: null,
    sort_order: 21,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race', 'sun-morning'],
  },
  {
    title: 'Shanghai: Shanghai Zoo Entry Ticket with Pandas',
    description: 'Meet China\'s iconic giant pandas up close in their naturalistic enclosure at Shanghai Zoo, then explore one of Asia\'s most diverse zoological collections. With over 6,000 animals representing 600+ species, Shanghai Zoo is a full-day wildlife destination in the heart of the city. The panda enclosure is the star attraction — a rare chance to see these beloved creatures in a well-maintained urban setting.',
    short_description: 'Entry ticket to Shanghai Zoo with the giant panda enclosure and over 600 species from across the globe.',
    abstract: 'Giant pandas up close at Shanghai Zoo — 6,000 animals, 600 species in the heart of the city. A$20 · 3 hrs · Budget-friendly race weekend wildlife stop.',
    category: 'adventure',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '20.00',
    price_currency: 'AUD',
    price_label: 'A$20',
    rating: '5.0',
    review_count: 9,
    image_url: 'https://cdn.getyourguide.com/img/tour/16714a8b7e02e13a63df962cf53da2ceb066a59729d3fa78e1684eb3db8ffd7b.png/medium.jpg',
    image_emoji: '🐼',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-wukang-road-city-walk-with-resident-storyteller-t1162696/',
    affiliate_product_id: 't1162696',
    is_featured: false,
    tag: null,
    sort_order: 22,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Yu Garden, Jade Temple, Bund & French Concession Tour',
    description: 'Discover the very best of Shanghai on this comprehensive 5-hour tour covering the Bund waterfront, the French Concession, Yu Garden, Old Town, and the Jade Buddha Temple. Enjoy tailored attention with a private guide and a flexible itinerary that moves at your pace. Round-trip transportation is provided from your hotel or cruise port, making it effortless to experience Shanghai\'s greatest highlights.',
    short_description: 'Private 5-hour Shanghai tour covering the Bund, French Concession, Yu Garden, and the Jade Buddha Temple with hotel transfers.',
    abstract: 'Bund, French Concession, Yu Garden, and Jade Buddha Temple in one private 5-hour tour with hotel transfers. A$200 · 5 hrs · Perfect race-day morning before 15:00.',
    category: 'adventure',
    duration_hours: '5.0',
    duration_label: '5 hrs',
    price_amount: '200.00',
    price_currency: 'AUD',
    price_label: 'A$200',
    rating: '5.0',
    review_count: 8,
    image_url: 'https://cdn.getyourguide.com/img/tour/64b7f0cac8673.jpeg/medium.jpg',
    image_emoji: '🏙️',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghaiyu-garden-jade-templebund-french-concession-tour-t488510/',
    affiliate_product_id: 't488510',
    is_featured: false,
    tag: null,
    sort_order: 23,
    windows: ['sun-morning'],
  },
  {
    title: 'Shanghai Guided Royal Banquet Photo with Massage Option',
    description: 'Be a guest of the ancient Chinese emperor at his imperial banquet. Taste royal cuisine, admire exquisite traditional dances and music, and dress in period costume for a regal photo session accompanied by a local guide. An optional Chinese massage rounds out this immersive experience of imperial culture. Surprisingly affordable and genuinely theatrical — a Shanghai must-do.',
    short_description: 'Imperial court banquet experience with royal cuisine, traditional performances, costume photos, and optional Chinese massage.',
    abstract: 'Imperial banquet, royal costume photos, traditional dancing, and optional massage — an affordable taste of ancient China. A$28 · 3 hrs · Any F1 evening or morning.',
    category: 'adventure',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '28.00',
    price_currency: 'AUD',
    price_label: 'A$28',
    rating: '5.0',
    review_count: 47,
    image_url: 'https://cdn.getyourguide.com/img/tour/1e2ed959eebe3765086e4d285318359614db77a0bbe14ec56890ffef72fbda45.jpeg/medium.jpg',
    image_emoji: '🎭',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-guided-royal-banquet-photo-incl-with-massage-opt-t858432/',
    affiliate_product_id: 't858432',
    is_featured: false,
    tag: null,
    sort_order: 24,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Oriental Pearl Tower Entry Ticket',
    description: 'Enjoy panoramic views of Shanghai from the iconic Oriental Pearl Tower — the colourful beacon of Pudong\'s skyline. Choose between 2 or 3 sphere levels for different elevations of breathtaking views across the Huangpu River, the Bund\'s historic waterfront, and the modern towers of Lujiazui. Includes a practical PDF guidebook and English online support. A Shanghai landmark experience at your own pace.',
    short_description: 'Entry ticket to the Oriental Pearl Tower with panoramic Pudong and Bund views from multiple sphere levels.',
    abstract: 'Shanghai\'s iconic pink tower — choose your sphere level for panoramic views across the Bund and Lujiazui. A$115 · 2 hrs · A race-day morning skyline moment.',
    category: 'adventure',
    duration_hours: '2.0',
    duration_label: '2 hrs',
    price_amount: '115.00',
    price_currency: 'AUD',
    price_label: 'A$115',
    rating: '4.4',
    review_count: 28,
    image_url: 'https://cdn.getyourguide.com/img/tour/54e574b7ad1a5d7405476e8cd4d0bedbe0f877c04977175265df4b598281b5c9.jpeg/medium.jpg',
    image_emoji: '🏙️',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-oriental-pearl-tower-e-ticket-includes-dining-t732062/',
    affiliate_product_id: 't732062',
    is_featured: false,
    tag: null,
    sort_order: 25,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },

  // =============================================
  // DAYTRIP (9)
  // =============================================
  {
    title: 'Shanghai: Zhujiajiao Private Tour w/ Boat Ride & Garden',
    description: 'Visit the charming Zhujiajiao water town — the "Oriental Venice" — just 45 minutes from Shanghai\'s city centre. Explore the unique township scenery with lively water markets along ancient stone-paved streets, take a relaxing gondola ride through winding canals under 36 stone bridges, and stroll through a beautiful classical Chinese garden. The perfect antidote to the modern megacity, best experienced as a race-day morning escape.',
    short_description: 'Private guided tour to Zhujiajiao water town with a gondola canal boat ride and classical Chinese garden visit.',
    abstract: '"Oriental Venice" Zhujiajiao — gondola ride, water markets, and 36 stone bridges, 45 minutes from Shanghai. A$195 · 5 hrs · The top race-morning day trip before 15:00.',
    category: 'daytrip',
    duration_hours: '5.0',
    duration_label: '5 hrs',
    price_amount: '195.00',
    price_currency: 'AUD',
    price_label: 'A$195',
    rating: '5.0',
    review_count: 461,
    image_url: 'https://cdn.getyourguide.com/img/tour/c4d2871460be470420d5be19427cf71649ef5d1e498b2f3f4bbce66248c65c13.jpg/medium.jpg',
    image_emoji: '⛵',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/zhujiajiao-water-town-private-tour-with-boat-ride-and-garden-t644054/',
    affiliate_product_id: 't644054',
    is_featured: true,
    tag: 'Most Popular',
    sort_order: 26,
    windows: ['sun-morning'],
  },
  {
    title: 'Shanghai: All-Inclusive Suzhou Day Trip by Bullet Train',
    description: 'Experience a tranquil escape from Shanghai on this all-inclusive guided day trip to Suzhou by bullet train. Travel in just 25 minutes to this picturesque riverside city celebrated for its centuries-old UNESCO World Heritage classical gardens, white-washed canal towns, and silk weaving heritage. Your guide handles everything — tickets, transfers, lunch, and entry fees — so you can simply enjoy the serenity of China\'s "garden city".',
    short_description: 'All-inclusive bullet train day trip to Suzhou to explore UNESCO classical gardens, silk heritage, and ancient canal towns.',
    abstract: 'All-inclusive Suzhou day trip by bullet train — UNESCO gardens, silk heritage, and ancient canals, 25 minutes from Shanghai. A$407 · 9 hrs · The ultimate race-morning cultural escape.',
    category: 'daytrip',
    duration_hours: '9.0',
    duration_label: '9 hrs',
    price_amount: '407.00',
    price_currency: 'AUD',
    price_label: 'A$407',
    rating: '5.0',
    review_count: 137,
    image_url: 'https://cdn.getyourguide.com/img/tour/64685a7780cbb.jpeg/medium.jpg',
    image_emoji: '🚄',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/all-inclusive-suzhou-day-tour-bullet-train-from-shanghai-t466570/',
    affiliate_product_id: 't466570',
    is_featured: true,
    tag: 'Top Rated',
    sort_order: 27,
    windows: ['sun-morning'],
  },
  {
    title: 'Yu Garden, Old Street, Bund & Zhujiajiao Water Town Bus Tour',
    description: 'See Shanghai\'s most important highlights in a single day on this comprehensive bus tour. Visit the Old Town and Yu Garden, stroll the famous Bund waterfront, and then ride out to the charming Zhujiajiao Water Town with its ancient bridges, canal markets, and waterway gondolas. The biggest advantage of this route is sheer coverage — all of Shanghai\'s must-see sites without the logistics headache.',
    short_description: 'Full-day bus tour covering Yu Garden, the Bund, and Zhujiajiao Water Town — Shanghai\'s greatest highlights in one day.',
    abstract: 'Yu Garden, Old Street, the Bund, and Zhujiajiao in one day — all of Shanghai\'s must-sees without the logistics. A$86 · 8 hrs · Best value race-morning discovery.',
    category: 'daytrip',
    duration_hours: '8.0',
    duration_label: '8 hrs',
    price_amount: '86.00',
    price_currency: 'AUD',
    price_label: 'A$86',
    rating: '4.7',
    review_count: 244,
    image_url: 'https://cdn.getyourguide.com/img/tour/027f4186e5bbfe36fd002709f331d95d080dbbd9a7b90e78ddbdbf592a442b0c.jpg/medium.jpg',
    image_emoji: '🏛️',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/yu-garden-old-street-bund-zhujiajiao-water-town-bus-tour-t959718/',
    affiliate_product_id: 't959718',
    is_featured: false,
    tag: null,
    sort_order: 28,
    windows: ['sun-morning'],
  },
  {
    title: 'Shanghai: 8-Hour Private City Tour',
    description: 'Explore Shanghai on a flexible full-day private tour with a knowledgeable guide. Follow the suggested itinerary or choose whichever sites interest you — from the futuristic Lujiazui towers to ancient temple districts, from the French Concession\'s tree-lined streets to the iconic Bund. Your private guide adapts the day to your interests and pace, making this the most versatile way to discover Shanghai.',
    short_description: 'Flexible 8-hour private Shanghai city tour — follow the suggested itinerary or customise your own route with a guide.',
    abstract: 'Full-day private Shanghai tour, fully flexible — follow the itinerary or choose your own route with your guide. A$191 · 8 hrs · Perfect race-morning deep dive.',
    category: 'daytrip',
    duration_hours: '8.0',
    duration_label: '8 hrs',
    price_amount: '191.00',
    price_currency: 'AUD',
    price_label: 'A$191',
    rating: '4.9',
    review_count: 231,
    image_url: 'https://cdn.getyourguide.com/img/tour/bb6dfdc6e86f4846b35c997691b211109bcc24f892e183a38d2171ee03cc782c.jpg/medium.jpg',
    image_emoji: '🚄',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/private-shanghai-day-tour-t61980/',
    affiliate_product_id: 't61980',
    is_featured: false,
    tag: null,
    sort_order: 29,
    windows: ['sun-morning'],
  },
  {
    title: 'Shanghai: Zoo and Zhujiajiao Water Town Tour with Boat Ride',
    description: 'Combine two of Shanghai\'s best day-out experiences in one private tour: a visit to Shanghai Zoo to see giant pandas and diverse wildlife, followed by an afternoon in the charming water town of Zhujiajiao with its ancient stone bridges and canal markets. Relax during a gondola boat ride through the town\'s waterways for a serene contrast to the city\'s frenetic energy.',
    short_description: 'Private tour combining Shanghai Zoo\'s giant pandas with Zhujiajiao Water Town canal gondola ride.',
    abstract: 'Shanghai Zoo giant pandas plus Zhujiajiao canal gondola in one private day — the best of wildlife and water towns. A$267 · 7 hrs · A memorable race-morning double.',
    category: 'daytrip',
    duration_hours: '7.0',
    duration_label: '7 hrs',
    price_amount: '267.00',
    price_currency: 'AUD',
    price_label: 'A$267',
    rating: '5.0',
    review_count: 56,
    image_url: 'https://cdn.getyourguide.com/img/tour/9f92d58a67b6661ca8396492b21facbbe8a0b497f07e0c0528a78f4d0cd48300.jpg/medium.jpg',
    image_emoji: '⛵',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-zoo-and-zhujiajiao-water-town-tour-with-boat-ride-t721139/',
    affiliate_product_id: 't721139',
    is_featured: false,
    tag: null,
    sort_order: 30,
    windows: ['sun-morning'],
  },
  {
    title: 'Shanghai: Private Shanghai & Zhujiajiao Tour with Lunch',
    description: 'Maximise your time with this private tour blending the ancient water town of Zhujiajiao with Shanghai\'s highlights in one seamless day. Explore Zhujiajiao by gondola boat ride then visit Shanghai\'s top sites — Yu Garden, the Bund, and Shanghai Tower — all at your private pace with lunch included. The most comprehensive way to experience both old and new Shanghai in a single day.',
    short_description: 'Private full-day tour combining Zhujiajiao water town with Yu Garden, the Bund, and Shanghai Tower, including lunch.',
    abstract: 'Zhujiajiao gondola, Yu Garden, the Bund, and Shanghai Tower all in one private day with lunch included. A$361 · 8 hrs · The premium race-morning Shanghai package.',
    category: 'daytrip',
    duration_hours: '8.0',
    duration_label: '8 hrs',
    price_amount: '361.00',
    price_currency: 'AUD',
    price_label: 'A$361',
    rating: '5.0',
    review_count: 115,
    image_url: 'https://cdn.getyourguide.com/img/tour/649ee5ad090a4.jpeg/medium.jpg',
    image_emoji: '⛵',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-private-shanghai-zhujiajiao-tour-with-lunch-t466565/',
    affiliate_product_id: 't466565',
    is_featured: false,
    tag: null,
    sort_order: 31,
    windows: ['sun-morning'],
  },
  {
    title: 'Shanghai: Private Guided Tour to Hangzhou by Bullet Train',
    description: 'Explore Hangzhou on a full-day private trip from Shanghai by bullet train. Customise your itinerary with your guide, visiting the legendary West Lake — one of China\'s most beautiful natural landscapes — alongside Lingyin Temple, Liuhe Pagoda, and Longjing Village, home of China\'s finest Dragon Well green tea. A private day of UNESCO heritage and natural beauty just 45 minutes from Shanghai.',
    short_description: 'Private full-day bullet train trip to Hangzhou with customisable itinerary covering West Lake, temples, and Dragon Well tea.',
    abstract: 'West Lake, Lingyin Temple, and Dragon Well tea in Hangzhou on a fully private bullet train day trip. A$444 · 9 hrs · A legendary Chinese landscape 45 mins from Shanghai.',
    category: 'daytrip',
    duration_hours: '9.0',
    duration_label: '9 hrs',
    price_amount: '444.00',
    price_currency: 'AUD',
    price_label: 'A$444',
    rating: '5.0',
    review_count: 108,
    image_url: 'https://cdn.getyourguide.com/img/tour/6498552893b13.jpeg/medium.jpg',
    image_emoji: '🚄',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/bullet-train-to-hangzhou-custom-private-tour-t466576/',
    affiliate_product_id: 't466576',
    is_featured: false,
    tag: null,
    sort_order: 32,
    windows: ['sun-morning'],
  },
  {
    title: 'Shanghai: Southern Great Wall Day Trip by Bullet Train',
    description: 'Get a Great Wall experience without the Beijing crowds — take a fast train from Shanghai to the Southern Great Wall section in Zhejiang Province. Walk ancient fortifications through dramatic mountain scenery, explore atmospheric old streets, and sample local food in a region rarely visited by international travellers. One of China\'s most epic day trips, departing from Shanghai on a bullet train.',
    short_description: 'Bullet train day trip from Shanghai to the Southern Great Wall in Zhejiang with ancient streets and mountain scenery.',
    abstract: 'Southern Great Wall by bullet train — ancient fortifications without Beijing\'s crowds, Zhejiang\'s dramatic mountains. A$560 · 13 hrs · The most epic race-morning adventure.',
    category: 'daytrip',
    duration_hours: '13.0',
    duration_label: '13 hrs',
    price_amount: '560.00',
    price_currency: 'AUD',
    price_label: 'A$560',
    rating: '4.9',
    review_count: 179,
    image_url: 'https://cdn.getyourguide.com/img/tour/5dffdd38005824d22c5d0fd3f6e5f628270986e36f6b3112b30399f683180ba7.jpeg/medium.jpg',
    image_emoji: '🏛️',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-southern-great-wall-day-trip-by-bullet-train-t703055/',
    affiliate_product_id: 't703055',
    is_featured: false,
    tag: null,
    sort_order: 33,
    windows: ['sun-morning'],
  },
  {
    title: 'Suzhou Private Guided Day Trip from Shanghai by Bullet Train',
    description: 'Travel by modern bullet train to the famed "Oriental Venice" of Suzhou on this fully escorted private day trip. Visit a UNESCO World Heritage classical garden with centuries-old rockeries and pavilions, stroll the lively water market at the old canal street, and take a relaxing boat ride along the Grand Canal — China\'s oldest and longest waterway. A serene, timeless counterpoint to Shanghai\'s relentless energy.',
    short_description: 'Private bullet train day trip to Suzhou with UNESCO classical gardens, canal boat ride, and historic water market.',
    abstract: 'Private Suzhou day trip by bullet train — UNESCO garden, Grand Canal boat ride, and ancient water market. A$307 · 9 hrs · Suzhou at its best before the race.',
    category: 'daytrip',
    duration_hours: '9.0',
    duration_label: '9 hrs',
    price_amount: '307.00',
    price_currency: 'AUD',
    price_label: 'A$307',
    rating: '5.0',
    review_count: 46,
    image_url: 'https://cdn.getyourguide.com/img/tour/3a3179874a0018b652bd1dac5a015a6fe41642990d4183f0ff5a233f1ceffc40.jpg/medium.jpg',
    image_emoji: '⛵',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/suzhou-private-guided-day-trip-from-shanghai-by-bullet-train-t640936/',
    affiliate_product_id: 't640936',
    is_featured: false,
    tag: null,
    sort_order: 34,
    windows: ['sun-morning'],
  },

  // =============================================
  // NIGHTLIFE (8)
  // =============================================
  {
    title: 'Shanghai: Night River Cruise Tour with Xinjiang Style Dining',
    description: 'Experience the very best of Shanghai on a private night cruise along the Huangpu River, combined with hotel or airport transfers and a spectacular Xinjiang-style halal dinner on board. Sail past the illuminated Bund and Pudong skylines while savouring authentic Central Asian cuisine — lamb skewers, flatbreads, and slow-cooked stews — in a unique dining experience on the water.',
    short_description: 'Private Huangpu River night cruise with Xinjiang-style halal dinner and spectacular illuminated skyline views.',
    abstract: 'Private Huangpu night cruise with Xinjiang halal dinner — the Bund and Pudong lit up from the water, food from Central Asia. A$217 · 3 hrs · The premium F1 evening experience.',
    category: 'nightlife',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '217.00',
    price_currency: 'AUD',
    price_label: 'A$217',
    rating: '5.0',
    review_count: 210,
    image_url: 'https://cdn.getyourguide.com/img/tour/640d58298cf82.jpeg/medium.jpg',
    image_emoji: '🚢',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-night-river-cruise-tour-with-xinjiang-style-dining-t450489/',
    affiliate_product_id: 't450489',
    is_featured: true,
    tag: 'Premium',
    sort_order: 35,
    windows: ['fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Huangpu Night Cruise: Cozy Vibe & Modern Shanghai Glow',
    description: 'Discover Shanghai\'s old-world charm and modern sparkle on a 45-minute Huangpu River cruise linking the Bund and Lujiazui. Watch the festive lights of the colonial Bund waterfront glow in contrast to Pudong\'s futuristic towers while drifting through the heart of the city. Nearby markets and street stalls await at both ends for a spontaneous post-cruise wander through a romantic Shanghai night.',
    short_description: '45-minute Huangpu River night cruise between the Bund and Lujiazui with illuminated skyline views.',
    abstract: '45-minute Huangpu cruise linking the Bund and Lujiazui — old-world colonial glow meets futuristic towers. A$30 · 1.5 hrs · The budget F1 evening river experience.',
    category: 'nightlife',
    duration_hours: '1.5',
    duration_label: '1.5 hrs',
    price_amount: '30.00',
    price_currency: 'AUD',
    price_label: 'A$30',
    rating: '4.3',
    review_count: 523,
    image_url: 'https://cdn.getyourguide.com/img/tour/b23cc19dcb1f6e03d4db7ac237067dbec5f04ac5555b5cc46cddcdbae896fbc1.jpg/medium.jpg',
    image_emoji: '🌙',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-huangpu-river-evening-cruise-ticket-t877317/',
    affiliate_product_id: 't877317',
    is_featured: false,
    tag: null,
    sort_order: 36,
    windows: ['fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai Night River Cruise VIP Seat with Authentic Dinner',
    description: 'Discover Shanghai\'s breathtaking city lights on a relaxing night cruise along the Huangpu River from a VIP seat. Admire the spectacular skylines and colonial buildings lit up along the waterfront while savouring a delightful local Shanghai dinner on board — steamed fish, braised pork belly, and classic Shanghai accompaniments. A refined, unhurried way to experience the city after dark.',
    short_description: 'VIP-seat Huangpu River night cruise with authentic Shanghai dinner and illuminated Bund and Pudong skyline views.',
    abstract: 'VIP seat on the Huangpu with authentic Shanghai dinner — steamed fish, braised pork belly, and colonial skylines. A$236 · 3 hrs · Sophisticated post-race F1 evening.',
    category: 'nightlife',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '236.00',
    price_currency: 'AUD',
    price_label: 'A$236',
    rating: '5.0',
    review_count: 55,
    image_url: 'https://cdn.getyourguide.com/img/tour/0dcc54a166ba07ea06b85ff337e6ee0255d61baa7f2a1eb65d61d0b65749c27a.jpg/medium.jpg',
    image_emoji: '🚢',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-night-river-cruise-vip-seat-with-authentic-dinner-t636715/',
    affiliate_product_id: 't636715',
    is_featured: false,
    tag: null,
    sort_order: 37,
    windows: ['fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Half-Day Old Shanghai Small Group Bike Tour (Day & Night)',
    description: 'Take a half-day guided bicycle tour through Old Shanghai in a small group of maximum 5 guests — the ideal size for a genuine local experience. Visit the Cite Bourgogne, Zhou Enlai\'s historic residence, and the restored Shanghai Old Street as your guide shares the cultural history of one of China\'s most storied cities. Available as a day or night tour, with the night version revealing a dramatically different side of Shanghai.',
    short_description: 'Small-group bicycle tour (max 5) through Old Shanghai covering historic residences, the Cite Bourgogne, and Old Street.',
    abstract: 'Max 5 guests cycling Old Shanghai — Zhou Enlai\'s residence, Cite Bourgogne, and Old Street by day or night. A$112 · 3 hrs · Great F1 morning or evening ride.',
    category: 'nightlife',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '112.00',
    price_currency: 'AUD',
    price_label: 'A$112',
    rating: '4.8',
    review_count: 128,
    image_url: 'https://cdn.getyourguide.com/img/tour/5b5abb5db2504.jpeg/medium.jpg',
    image_emoji: '🚴',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/half-day-old-shanghai-bike-tour-t15841/',
    affiliate_product_id: 't15841',
    is_featured: false,
    tag: null,
    sort_order: 38,
    windows: ['fri-morning', 'sat-morning', 'fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: '4-Hour Shanghai Pub Crawl (bars & nightclub hopping)',
    description: 'Welcome to Shanghai\'s No.1 nightlife tour — if you love trying different drinks, making new friends, and exploring the city\'s electric bar scene, this is made for you. Hop between Shanghai\'s best bars and nightclubs with a group of like-minded travellers, enjoy complimentary shots, skip-the-line entry, and let your guide take you through the French Concession\'s most vibrant nightlife strip.',
    short_description: 'Shanghai\'s top-rated 4-hour pub crawl through the city\'s best bars and nightclubs with complimentary shots and skip-the-line entry.',
    abstract: 'Shanghai\'s No.1 nightlife tour — 4 hours, best bars, complimentary shots, and new friends in the French Concession. A$34 · 4 hrs · The quintessential F1 Friday night.',
    category: 'nightlife',
    duration_hours: '4.0',
    duration_label: '4 hrs',
    price_amount: '34.00',
    price_currency: 'AUD',
    price_label: 'A$34',
    rating: '4.8',
    review_count: 190,
    image_url: 'https://cdn.getyourguide.com/img/tour/bb025edaf098e89d7aa56d48d403f9afdfd868a573908e6830057bc6a1032e41.jpg/medium.jpg',
    image_emoji: '🍺',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/4-hour-shanghai-pub-crawl-bars-nightclub-hopping-t643749/',
    affiliate_product_id: 't643749',
    is_featured: false,
    tag: null,
    sort_order: 39,
    windows: ['fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Nightlife Adventure and Tasting Bike Tour',
    description: 'Discover Shanghai at night on an e-scooter tasting tour through the city\'s most electrifying neighbourhoods. See the Bund\'s glittering skyline from the waterfront promenade, zip through the lantern-lit Yu Garden, and ride down lively Nanjing Road for a mix of modern LED spectacle and ancient architectural charm. Stop for street food tastings along the way — the city tastes as good as it looks after dark.',
    short_description: 'Night e-scooter tasting tour through Shanghai stopping at the illuminated Bund, Yu Garden, and Nanjing Road.',
    abstract: 'E-scooter through illuminated Bund, lantern-lit Yu Garden, and Nanjing Road with street food tastings. A$63 · 3 hrs · Shanghai at night, exactly as it should be.',
    category: 'nightlife',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '63.00',
    price_currency: 'AUD',
    price_label: 'A$63',
    rating: '4.6',
    review_count: 107,
    image_url: 'https://cdn.getyourguide.com/img/tour/5b2df01952541.jpeg/medium.jpg',
    image_emoji: '🌙',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-3-hour-nightlife-adventure-tasting-by-e-scooter-t162626/',
    affiliate_product_id: 't162626',
    is_featured: false,
    tag: null,
    sort_order: 40,
    windows: ['fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai: Bar Hopping Tour',
    description: 'Get ready for the most festive nightlife experience in Shanghai\'s French Concession. Join this bar hopping tour and explore the area\'s most vibrant and unique bars — from intimate speakeasies to buzzing cocktail bars — with an international group of travellers. Sample signature cocktails, meet new people, and discover why the French Concession has one of Asia\'s best bar scenes.',
    short_description: 'Bar hopping tour through the French Concession\'s best bars with an international group and signature cocktails.',
    abstract: 'French Concession bar hopping with an international crowd — signature cocktails and the best bars in one of Asia\'s great nightlife districts. A$41 · 3 hrs · F1 Friday or Saturday evening must.',
    category: 'nightlife',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '41.00',
    price_currency: 'AUD',
    price_label: 'A$41',
    rating: '4.8',
    review_count: 87,
    image_url: 'https://cdn.getyourguide.com/img/tour/e8d90f77305aa740b5e1231fe0b10651022f084b4b193e5f7c3c815a37d41f00.jpeg/medium.jpg',
    image_emoji: '🍺',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/shanghai-bar-hopping-tour-in-the-former-french-concession-t763728/',
    affiliate_product_id: 't763728',
    is_featured: false,
    tag: null,
    sort_order: 41,
    windows: ['fri-evening', 'sat-evening', 'post-race'],
  },
  {
    title: 'Shanghai Charming Night Small Group Bike Tour',
    description: 'Explore Shanghai\'s colourful nightlife, spectacular skyline views, and dazzling light shows on this small-group night cycling tour. Ride through the French Concession\'s tree-lined avenues and past Xintiandi\'s outdoor bars and restaurants before finishing at the Bund for a breathtaking panoramic view of the city\'s illuminated skyline. The perfect two-wheeled way to end a race weekend day in Shanghai.',
    short_description: 'Small-group night bike tour through the French Concession and Xintiandi finishing with skyline views from the Bund.',
    abstract: 'Night cycling through the French Concession and Xintiandi, finishing at the Bund\'s illuminated skyline. A$124 · 3 hrs · The perfect race-night ride.',
    category: 'nightlife',
    duration_hours: '3.0',
    duration_label: '3 hrs',
    price_amount: '124.00',
    price_currency: 'AUD',
    price_label: 'A$124',
    rating: '4.9',
    review_count: 12,
    image_url: 'https://cdn.getyourguide.com/img/tour/5d0c0b6eb8732.jpeg/medium.jpg',
    image_emoji: '🚴',
    affiliate_base_url: 'https://www.getyourguide.com/shanghai-l178/4-hour-night-cycling-tour-of-shanghai-t15906/',
    affiliate_product_id: 't15906',
    is_featured: false,
    tag: null,
    sort_order: 42,
    windows: ['fri-evening', 'sat-evening', 'post-race'],
  },
];

async function seed() {
  const pool = mysql.createPool({
    host: process.env.DATABASE_HOST ?? 'localhost',
    port: Number(process.env.DATABASE_PORT) || 3306,
    user: process.env.DATABASE_USER ?? 'root',
    password: process.env.DATABASE_PASSWORD ?? '12345678',
    database: process.env.DATABASE_NAME ?? 'pitlane',
  });

  const db = drizzle(pool);

  console.log('[seed-exp] Connected to database');

  // --- 1. Look up the Shanghai 2026 race ---
  const [race] = await db.select().from(races).where(eq(races.slug, 'shanghai-2026'));
  if (!race) {
    console.log('[seed-exp] ERROR: Shanghai 2026 race not found. Run seed-shanghai-race.ts first.');
    await pool.end();
    return;
  }
  const raceId = race.id;
  console.log('[seed-exp] Found race: shanghai-2026 (id:', raceId, ')');

  // --- 2. Check idempotency ---
  const existing = await db.select().from(experiences).where(eq(experiences.race_id, raceId)).limit(1);
  if (existing.length > 0) {
    console.log('[seed-exp] Experiences already seeded for race id:', raceId);
    console.log('[seed-exp] To re-seed, delete existing data first:');
    console.log(`  DELETE FROM experience_windows_map WHERE experience_id IN (SELECT id FROM experiences WHERE race_id = ${raceId});`);
    console.log(`  DELETE FROM experiences WHERE race_id = ${raceId};`);
    await pool.end();
    return;
  }

  // --- 3. Build window slug -> id lookup ---
  const windows = await db.select().from(experience_windows).where(eq(experience_windows.race_id, raceId));
  const windowBySlug = new Map(windows.map(w => [w.slug, w.id]));
  console.log('[seed-exp] Found', windows.length, 'experience windows');

  if (windows.length === 0) {
    console.log('[seed-exp] ERROR: No experience windows found. Run seed-shanghai-race.ts first.');
    await pool.end();
    return;
  }

  // --- 4. Insert each experience + window mappings ---
  let totalMappings = 0;

  for (const exp of EXPERIENCES) {
    const slug = exp.title
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '')
      .replace(/[\s_]+/g, '-')
      .replace(/^-+|-+$/g, '');

    // Insert experience with placeholder affiliate URL
    const [result] = await db.insert(experiences).values({
      race_id: raceId,
      title: exp.title,
      slug,
      description: exp.description,
      short_description: exp.short_description,
      abstract: exp.abstract ?? null,
      category: exp.category,
      duration_hours: exp.duration_hours,
      duration_label: exp.duration_label,
      price_amount: exp.price_amount,
      price_currency: exp.price_currency,
      price_label: exp.price_label,
      rating: exp.rating,
      review_count: exp.review_count,
      image_url: exp.image_url,
      image_emoji: exp.image_emoji,
      affiliate_partner: 'getyourguide',
      affiliate_url: '',
      affiliate_product_id: exp.affiliate_product_id,
      is_featured: exp.is_featured,
      tag: exp.tag,
      sort_order: exp.sort_order,
      is_active: true,
    });

    const experienceId = result.insertId;

    // Build affiliate URL with real DB id and update the row
    const affiliateUrl = buildAffiliateUrl(exp.affiliate_base_url, experienceId, 'feed');
    await db.update(experiences)
      .set({ affiliate_url: affiliateUrl })
      .where(eq(experiences.id, experienceId));

    // Insert window mappings
    for (const windowSlug of exp.windows) {
      const windowId = windowBySlug.get(windowSlug);
      if (!windowId) {
        console.warn(`[seed-exp] WARNING: Window slug "${windowSlug}" not found, skipping`);
        continue;
      }
      await db.insert(experience_windows_map).values({
        experience_id: experienceId,
        window_id: windowId,
      });
      totalMappings++;
    }

    console.log(`[seed-exp] Inserted: ${exp.title} (${exp.windows.length} windows)`);
  }

  // --- Done ---
  console.log(`[seed-exp] Done! Seeded ${EXPERIENCES.length} experiences with ${totalMappings} window mappings`);
  await pool.end();
}

seed().catch((err) => {
  console.error('[seed-exp] Failed:', err);
  process.exit(1);
});
